package com.g2k.calendy.utils;

import java.util.ArrayList;
import java.util.Collections;

/**
 * Calendar to hold ArrayList of Tasks
 * Each calendar has one owner that can add or delete tasks
 * Subscribers can only access the tasks
 * UID is generated by Firebase upon registration
 * @author Mehmet Kağan İlbak
 * @version 2021/05/03
 */
public class Calendar {
    private ArrayList<Task> tasks;
    private ArrayList<String> subscriberUIDs;
    private String ownerUID;
    private String name;
    private boolean isPublic;

    public String getOwnerUID() {
        return ownerUID;
    }

    public Calendar(String name, boolean isPublic, String ownerUID) {
        tasks = new ArrayList<>();
        subscriberUIDs = new ArrayList<>();
        this.name = name;
        this.ownerUID = ownerUID;
        this.isPublic = isPublic;
    }

    public Calendar() {
        // Required for database
    }

    public void addTask(Task task) {
        tasks.add(task);
//        Collections.sort(tasks);
    }

    public Task getNextTask() {
        if (tasks.size() > 0)
            return tasks.get(0);
        return null; // TODO fix this
    }

    public int getTaskCount() {
        return tasks.size();
    }

    public void removeCurrentTask() {
        tasks.remove(0);
    }

    public void removeTask(int index) {
        tasks.remove(index);
    }

    public String getName() {
        return name;
    }

    public boolean isPublic() {
        return isPublic;
    }

    public void setPublic(boolean aPublic) {
        isPublic = aPublic;
    }
}